spring:
  profiles:
    default: default
  application:
    name: auth-service
  h2:
    console:
      enabled: true
  config:
    import: "configserver:http://localhost:8888"

  datasource:
    url: jdbc:h2:mem:users;
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


server:
  port: 3030
  servlet:
    context-path: /auth-service

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/