server:
  servlet:
    context-path: /admin-core-service
  port: 8082

spring:
  application:
    name: admin-core-service

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    hikari:
      connection-timeout: ${db.connection-timeout}
      maximum-pool-size: ${db.maximum-pool-size}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
