server:
  servlet:
    context-path: /notificacion-service
  port: 8083

spring:
  application:
    name: notificacion-service
  datasource:
    url: none
  jpa:
    database-platform: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/