spring:
  application:
    name: notificacion-service
    server:
      port: 8080

twilio:
  account:
    sid: ${TWILIO_SID}
  auth:
    token: ${TWILIO_TOKEN}
  whatsapp:
    from: +14155238886
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/